// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl0jcHLQtb10Dc3q1vXJetICXPjc0iqyA',
    appId: '1:329823172154:web:413b456609d6d1252ae703',
    messagingSenderId: '329823172154',
    projectId: 'todolist-app-1f7a4',
    authDomain: 'todolist-app-1f7a4.firebaseapp.com',
    storageBucket: 'todolist-app-1f7a4.appspot.com',
    measurementId: 'G-HLFSMKFT7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQVjD5mk9VxIGdjdQpXXlmwDnA-WMeoLQ',
    appId: '1:329823172154:android:ea4b720e5c404f462ae703',
    messagingSenderId: '329823172154',
    projectId: 'todolist-app-1f7a4',
    storageBucket: 'todolist-app-1f7a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtLZq6pGluHu1SywJcDol1PaVaYCgzH4',
    appId: '1:329823172154:ios:6e9ed28310f60d1c2ae703',
    messagingSenderId: '329823172154',
    projectId: 'todolist-app-1f7a4',
    storageBucket: 'todolist-app-1f7a4.appspot.com',
    iosClientId: '329823172154-j74hms2886kcjgp2ogsj9cqp75v443di.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtLZq6pGluHu1SywJcDol1PaVaYCgzH4',
    appId: '1:329823172154:ios:6e9ed28310f60d1c2ae703',
    messagingSenderId: '329823172154',
    projectId: 'todolist-app-1f7a4',
    storageBucket: 'todolist-app-1f7a4.appspot.com',
    iosClientId: '329823172154-j74hms2886kcjgp2ogsj9cqp75v443di.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl0jcHLQtb10Dc3q1vXJetICXPjc0iqyA',
    appId: '1:329823172154:web:2c62b5673b7effd12ae703',
    messagingSenderId: '329823172154',
    projectId: 'todolist-app-1f7a4',
    authDomain: 'todolist-app-1f7a4.firebaseapp.com',
    storageBucket: 'todolist-app-1f7a4.appspot.com',
    measurementId: 'G-39W704E0R7',
  );
}
